// Minimal ABI for frontend interaction with BountyEscrow + MockUSDC
// Full ABI is generated by Foundry → copy from contracts/out/BountyEscrow.sol/BountyEscrow.json

export const BOUNTY_ESCROW_ABI = [
  // Enterprise
  {
    name: 'depositBounty',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'datasetId', type: 'bytes32' },
      { name: 'amount', type: 'uint256' },
      { name: 'rewardPerTask', type: 'uint256' },
      { name: 'totalTasks', type: 'uint256' },
    ],
    outputs: [],
  },
  // Worker
  {
    name: 'claimBalance',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'workerBalance',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'worker', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  // View
  {
    name: 'getBounty',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'datasetId', type: 'bytes32' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'enterprise', type: 'address' },
          { name: 'totalDeposit', type: 'uint256' },
          { name: 'remaining', type: 'uint256' },
          { name: 'rewardPerTask', type: 'uint256' },
          { name: 'totalTasks', type: 'uint256' },
          { name: 'completedTasks', type: 'uint256' },
          { name: 'active', type: 'bool' },
        ],
      },
    ],
  },
  // Events
  {
    name: 'BountyDeposited',
    type: 'event',
    inputs: [
      { name: 'datasetId', type: 'bytes32', indexed: true },
      { name: 'enterprise', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256' },
      { name: 'rewardPerTask', type: 'uint256' },
      { name: 'totalTasks', type: 'uint256' },
    ],
  },
  {
    name: 'PaymentDistributed',
    type: 'event',
    inputs: [
      { name: 'worker', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256' },
    ],
  },
] as const

export const MOCK_USDC_ABI = [
  {
    name: 'approve',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'allowance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'decimals',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
] as const

// ── Contract addresses ────────────────────────────────────────────────────
export const BOUNTY_ESCROW_ADDRESS = (
  process.env.NEXT_PUBLIC_BOUNTY_ESCROW_ADDRESS ?? '0x0000000000000000000000000000000000000000'
) as `0x${string}`

export const MOCK_USDC_ADDRESS = (
  process.env.NEXT_PUBLIC_MOCK_USDC_ADDRESS ?? '0x0000000000000000000000000000000000000000'
) as `0x${string}`

// ── Constants ─────────────────────────────────────────────────────────────
export const USDC_DECIMALS = 6
export const REWARD_PER_TASK = 100_000n // 0.1 USDC in micro-units
